# Site settings
title: Eaten by Grues
email: gruebait@eatenbygrues.com
description: > # this means to ignore newlines until "baseurl:"
  It is pitch black here. You are likely to be eaten by a grue.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eatenbygrues.com" # the base hostname & protocol for your site
twitter_username: iamgruebait
github_username:  gruebait
permalink: /:categories/:title

# Build settings
markdown: kramdown

################################################################################
# Collections
################################################################################

collections:
  projects:
    output: true
    permalink: /projects/:path/

################################################################################
# Defaults
################################################################################

defaults:
  -
    scope:
      path: "projects"
    values:
      bodyclass: project single
